language: ruby

before_install:
  - gem install bundler -v "~> 1.17"

rvm:
  - 2.2.8
  - 2.3.5
  - 2.4.2
  - 2.5.0
  - ruby-head

sudo: false

script:
  - bundle exec rake code_analysis
  - bundle exec rspec
